import bcrypt from 'bcryptjs';
import { pool, query } from './db.js';

const users = [['Admin User','admin@fundsroom.local','Admin'],['Sales User','sales@fundsroom.local','Sales'],['Warehouse User','warehouse@fundsroom.local','Warehouse'],['Accounts User','accounts@fundsroom.local','Accounts']];
const customers = [['Ananya Mehta','9876543210','orders@ananyatraders.in','Ananya Traders','Wholesale','Active','Pune, Maharashtra','Priority wholesale account'],['Rohan Kulkarni','9876501122','procurement@saiindustries.in','Sai Industries','Distributor','Active','Mumbai, Maharashtra','Monthly replenishment customer'],['Meera Joshi','9876502233','meera@greenfieldretail.in','Greenfield Retail','Retail','Lead','Nashik, Maharashtra','Requested product catalogue'],['Arjun Shah','9876503344','buying@vertexsupplies.in','Vertex Supplies','Distributor','Active','Ahmedabad, Gujarat','New distributor onboarding'],['Priya Nair','9876504455','priya@bluepeaktrading.in','Bluepeak Trading Co.','Wholesale','Inactive','Bengaluru, Karnataka','Follow up next quarter']];
const products = [['Industrial Fastener Set','IFS-001','Hardware',1250,48,10,'Warehouse A'],['Safety Gloves','SG-002','Safety',220,18,25,'Warehouse B'],['PVC Pipe 2 inch','PVP-003','Plumbing',340,85,20,'Warehouse A'],['Cordless Drill 18V','CDR-004','Power Tools',4800,14,5,'Warehouse C'],['Industrial Adhesive 5L','IAD-005','Consumables',890,32,10,'Warehouse B'],['Protective Helmet','PHM-006','Safety',650,56,15,'Warehouse B']];

async function seed() {
  const hash=await bcrypt.hash('Password@123',10);
  for(const [name,email,role] of users) await query('INSERT INTO users(name,email,password_hash,role) VALUES($1,$2,$3,$4) ON CONFLICT(email) DO NOTHING',[name,email,hash,role]);
  for(const customer of customers) await query('INSERT INTO customers(name,mobile,email,business_name,customer_type,status,address,notes) SELECT $1::varchar,$2::varchar,$3::varchar,$4::varchar,$5::varchar,$6::varchar,$7::text,$8::text WHERE NOT EXISTS (SELECT 1 FROM customers WHERE mobile=$2::varchar)',customer);
  for(const product of products) await query('INSERT INTO products(name,sku,category,unit_price,current_stock,min_stock_alert,warehouse_location) VALUES($1,$2,$3,$4,$5,$6,$7) ON CONFLICT(sku) DO NOTHING',product);
  const exists=await query("SELECT id FROM challans WHERE challan_number='CH-2026-100001'");
  if(!exists.rowCount){const client=await pool.connect();try{await client.query('BEGIN');const admin=(await client.query("SELECT id FROM users WHERE email='admin@fundsroom.local'")).rows[0],customer=(await client.query("SELECT id FROM customers WHERE mobile='9876543210'")).rows[0],fasteners=(await client.query("SELECT * FROM products WHERE sku='IFS-001' FOR UPDATE")).rows[0],pipes=(await client.query("SELECT * FROM products WHERE sku='PVP-003' FOR UPDATE")).rows[0],challan=(await client.query("INSERT INTO challans(challan_number,customer_id,total_quantity,status,created_by) VALUES('CH-2026-100001',$1,5,'Confirmed',$2) RETURNING id",[customer.id,admin.id])).rows[0];for(const [product,quantity] of [[fasteners,2],[pipes,3]] as const){await client.query('INSERT INTO challan_items(challan_id,product_id,product_name,sku,unit_price,quantity) VALUES($1,$2,$3,$4,$5,$6)',[challan.id,product.id,product.name,product.sku,product.unit_price,quantity]);await client.query('UPDATE products SET current_stock=current_stock-$1 WHERE id=$2',[quantity,product.id]);await client.query("INSERT INTO stock_movements(product_id,quantity_changed,movement_type,reason,created_by) VALUES($1,$2,'OUT',$3,$4)",[product.id,quantity,'Confirmed challan CH-2026-100001',admin.id])}await client.query('COMMIT')}catch(error){await client.query('ROLLBACK');throw error}finally{client.release()}}
  console.log('Demo data ready. Password for every seeded account: Password@123'); await pool.end();
}
seed().catch(error=>{console.error(error);process.exit(1)});
